#!/bin/bash
question_number=${1:-1}
day=${2:-$(date +%d)}
year=${3:-$(date +%Y)}
command="cp -n ./template.ts ./day${day}/question-${question_number}.ts"
echo running... ${command}

mkdir -p "./day${day}"
touch "./day${day}/input-test.txt"
touch "./day${day}/input.txt"

source .env && curl -s "https://adventofcode.com/${year}/day/${day}/input" \
  --cookie "session=${AOC_SESSION_ID}" \
  --output "./day${day}/input.txt"

${command}
